[mgr]
show_hidden = true

[[opener.bulk-rename]]
run   = "nvim %s"
block = true

[[opener.set-wallpaper]]
run = '''osascript -e 'on run {img}' -e 'tell application "System Events" to set picture of every desktop to img' -e 'end run' %s1'''
desc = "Set as wallpaper"

[[open.prepend_rules]]
url = "bulk-rename.txt"
use = "bulk-rename"

[[open.prepend_rules]]
mime = "image/*"
use  = ["set-wallpaper", "open"]
